source 'https://rubygems.org'

gem 'rails', '4.2.0.beta1'
gem 'sass-rails', '~> 5.0.0.beta1'
gem 'uglifier', '>= 1.3.0'
gem 'rails-html-sanitizer', '~> 1.0'
gem 'breadcrumbs', path: '../..'

group :development, :test do
  gem 'spring'
end

